ls:
  .dir: kebab-case
  .md: kebab-case | regex:[0-9A-Z\-]+
  .js: kebab-case
  .spec.js: kebab-case
  .config.js: kebab-case

ignore:
  - .git
  - node_modules
  - .github
  - .vscode
  - .template-solution
